coverage:
  status:
    project:
      default:
        # basic
        target: 0%
        threshold: 10%
        patch: false
        flags:
          - unit
       # advanced settings
        branches:
          - master
        if_ci_failed: error #success, failure, error, ignore
        informational: false
        only_pulls: false
