name: cypress-test-run
on:
  push:
    branches: ['master', 'master-stable', 'prod-beta', 'prod-stable']
  pull_request:
    branches: ['master']
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    env:
      BRANCH: "${{ github.ref_name }}:-${{ github.head_ref }}"
      TRAVIS_PULL_REQUEST_BRANCH: ${{ github.ref_name }}
      TRAVIS_BRANCH: ${{ github.head_ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Jest tests
        run: npm run test
      - name: Component tests
        run: npm run test:ct
      - name: Create coverage
        run: npm run coverage
      - name: Deploy
        run: npm run travis:verify && curl -sSL https://raw.githubusercontent.com/RedHatInsights/insights-frontend-builder-common/master/src/bootstrap.sh | bash -s
